# Generated by Django 5.2.9 on 2026-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0011_deploymentdescriptor_artifact_repo_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfdeploymentinstance',
            name='user_provided_namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
